spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
#
##  flyway:
##    url: ${DB_URL}
##    user: ${DB_USERNAME}
##    password: ${DB_PASSWORD}
#
  jpa:
    database: POSTGRESQL
    show-sql: true
#    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

server:
  port: 9998

#springdoc:
#  swagger-ui:
#    disable-swagger-default-url: true
#    path: /swagger-ui.html
